export default [
  {  key: 'AF', flag: 'af', value: 'Afghanistan', label: 'Afghanistan', },
  {  key: 'AX', flag: 'ax', value: '\u00c5land Islands', label: '\u00c5land Islands', },
  {  key: 'AL', flag: 'al', value: 'Albania', label: 'Albania', },
  {  key: 'DZ', flag: 'dz', value: 'Algeria', label: 'Algeria', },
  {  key: 'AS', flag: 'as', value: 'American Samoa', label: 'American Samoa', },
  {  key: 'AD', flag: 'ad', value: 'Andorra', label: 'Andorra', },
  {  key: 'AO', flag: 'ao', value: 'Angola', label: 'Angola', },
  {  key: 'AI', flag: 'ai', value: 'Anguilla', label: 'Anguilla', },
  {  key: 'AG', flag: 'ag', value: 'Antigua & Barbuda', label: 'Antigua & Barbuda', },
  {  key: 'AR', flag: 'ar', value: 'Argentina', label: 'Argentina', },
  {  key: 'AM', flag: 'am', value: 'Armenia', label: 'Armenia', },
  {  key: 'AW', flag: 'aw', value: 'Aruba', label: 'Aruba', },
  {  key: 'AU', flag: 'au', value: 'Australia', label: 'Australia', },
  {  key: 'AT', flag: 'at', value: 'Austria', label: 'Austria', },
  {  key: 'AZ', flag: 'az', value: 'Azerbaijan', label: 'Azerbaijan', },
  {  key: 'BS', flag: 'bs', value: 'Bahamas', label: 'Bahamas', },
  {  key: 'BH', flag: 'bh', value: 'Bahrain', label: 'Bahrain', },
  {  key: 'BD', flag: 'bd', value: 'Bangladesh', label: 'Bangladesh', },
  {  key: 'BB', flag: 'bb', value: 'Barbados', label: 'Barbados', },
  {  key: 'BY', flag: 'by', value: 'Belarus', label: 'Belarus', },
  {  key: 'BE', flag: 'be', value: 'Belgium', label: 'Belgium', },
  {  key: 'BZ', flag: 'bz', value: 'Belize', label: 'Belize', },
  {  key: 'BJ', flag: 'bj', value: 'Benin', label: 'Benin', },
  {  key: 'BM', flag: 'bm', value: 'Bermuda', label: 'Bermuda', },
  {  key: 'BT', flag: 'bt', value: 'Bhutan', label: 'Bhutan', },
  {  key: 'BO', flag: 'bo', value: 'Bolivia', label: 'Bolivia', },
  {  key: 'BA', flag: 'ba', value: 'Bosnia & Herzegovina', label: 'Bosnia & Herzegovina', },
  {  key: 'BW', flag: 'bw', value: 'Botswana', label: 'Botswana', },
  {  key: 'BR', flag: 'br', value: 'Brazil', label: 'Brazil', },
  {  key: 'IO', flag: 'io', value: 'British Indian Ocean Territory', label: 'British Indian Ocean Territory', },
  {  key: 'VG', flag: 'vg', value: 'British Virgin Islands', label: 'British Virgin Islands', },
  {  key: 'BN', flag: 'bn', value: 'Brunei', label: 'Brunei', },
  {  key: 'BG', flag: 'bg', value: 'Bulgaria', label: 'Bulgaria', },
  {  key: 'BF', flag: 'bf', value: 'Burkina Faso', label: 'Burkina Faso', },
  {  key: 'BI', flag: 'bi', value: 'Burundi', label: 'Burundi', },
  {  key: 'KH', flag: 'kh', value: 'Cambodia', label: 'Cambodia', },
  {  key: 'CM', flag: 'cm', value: 'Cameroon', label: 'Cameroon', },
  {  key: 'CA', flag: 'ca', value: 'Canada', label: 'Canada', },
  {  key: 'CV', flag: 'cv', value: 'Cape Verde', label: 'Cape Verde', },
  {  key: 'KY', flag: 'ky', value: 'Cayman Islands', label: 'Cayman Islands', },
  {  key: 'CF', flag: 'cf', value: 'Central African Republic', label: 'Central African Republic', },
  {  key: 'TD', flag: 'td', value: 'Chad', label: 'Chad', },
  {  key: 'CL', flag: 'cl', value: 'Chile', label: 'Chile', },
  {  key: 'CN', flag: 'cn', value: 'China', label: 'China', },
  {  key: 'CX', flag: 'cx', value: 'Christmas Island', label: 'Christmas Island', },
  {  key: 'CC', flag: 'cc', value: 'Cocos (Keeling) Islands', label: 'Cocos (Keeling) Islands', },
  {  key: 'CO', flag: 'co', value: 'Colombia', label: 'Colombia', },
  {  key: 'KM', flag: 'km', value: 'Comoros', label: 'Comoros', },
  {  key: 'CG', flag: 'cg', value: 'Congo - Brazzaville', label: 'Congo - Brazzaville', },
  {  key: 'CD', flag: 'cd', value: 'Congo - Kinshasa', label: 'Congo - Kinshasa', },
  {  key: 'CK', flag: 'ck', value: 'Cook Islands', label: 'Cook Islands', },
  {  key: 'CR', flag: 'cr', value: 'Costa Rica', label: 'Costa Rica', },
  {  key: 'CI', flag: 'ci', value: 'C\u00f4te d\u2019Ivoire', label: 'C\u00f4te d\u2019Ivoire', },
  {  key: 'HR', flag: 'hr', value: 'Croatia', label: 'Croatia', },
  {  key: 'CU', flag: 'cu', value: 'Cuba', label: 'Cuba', },
  {  key: 'CY', flag: 'cy', value: 'Cyprus', label: 'Cyprus', },
  {  key: 'CZ', flag: 'cz', value: 'Czech Republic', label: 'Czech Republic', },
  {  key: 'DK', flag: 'dk', value: 'Denmark', label: 'Denmark', },
  {  key: 'DJ', flag: 'dj', value: 'Djibouti', label: 'Djibouti', },
  {  key: 'DM', flag: 'dm', value: 'Dominica', label: 'Dominica', },
  {  key: 'DO', flag: 'do', value: 'Dominican Republic', label: 'Dominican Republic', },
  {  key: 'EC', flag: 'ec', value: 'Ecuador', label: 'Ecuador', },
  {  key: 'EG', flag: 'eg', value: 'Egypt', label: 'Egypt', },
  {  key: 'SV', flag: 'sv', value: 'El Salvador', label: 'El Salvador', },
  {  key: 'GQ', flag: 'gq', value: 'Equatorial Guinea', label: 'Equatorial Guinea', },
  {  key: 'ER', flag: 'er', value: 'Eritrea', label: 'Eritrea', },
  {  key: 'EE', flag: 'ee', value: 'Estonia', label: 'Estonia', },
  {  key: 'ET', flag: 'et', value: 'Ethiopia', label: 'Ethiopia', },
  {  key: 'FK', flag: 'fk', value: 'Falkland Islands', label: 'Falkland Islands', },
  {  key: 'FO', flag: 'fo', value: 'Faroe Islands', label: 'Faroe Islands', },
  {  key: 'FJ', flag: 'fj', value: 'Fiji', label: 'Fiji', },
  {  key: 'FI', flag: 'fi', value: 'Finland', label: 'Finland', },
  {  key: 'FR', flag: 'fr', value: 'France', label: 'France', },
  {  key: 'GF', flag: 'gf', value: 'French Guiana', label: 'French Guiana', },
  {  key: 'PF', flag: 'pf', value: 'French Polynesia', label: 'French Polynesia', },
  {  key: 'TF', flag: 'tf', value: 'French Southern Territories', label: 'French Southern Territories', },
  {  key: 'GA', flag: 'ga', value: 'Gabon', label: 'Gabon', },
  {  key: 'GM', flag: 'gm', value: 'Gambia', label: 'Gambia', },
  {  key: 'GE', flag: 'ge', value: 'Georgia', label: 'Georgia', },
  {  key: 'DE', flag: 'de', value: 'Germany', label: 'Germany', },
  {  key: 'GH', flag: 'gh', value: 'Ghana', label: 'Ghana', },
  {  key: 'GI', flag: 'gi', value: 'Gibraltar', label: 'Gibraltar', },
  {  key: 'GR', flag: 'gr', value: 'Greece', label: 'Greece', },
  {  key: 'GL', flag: 'gl', value: 'Greenland', label: 'Greenland', },
  {  key: 'GD', flag: 'gd', value: 'Grenada', label: 'Grenada', },
  {  key: 'GP', flag: 'gp', value: 'Guadeloupe', label: 'Guadeloupe', },
  {  key: 'GU', flag: 'gu', value: 'Guam', label: 'Guam', },
  {  key: 'GT', flag: 'gt', value: 'Guatemala', label: 'Guatemala', },
  {  key: 'GN', flag: 'gn', value: 'Guinea', label: 'Guinea', },
  {  key: 'GW', flag: 'gw', value: 'Guinea-Bissau', label: 'Guinea-Bissau', },
  {  key: 'GY', flag: 'gy', value: 'Guyana', label: 'Guyana', },
  {  key: 'HT', flag: 'ht', value: 'Haiti', label: 'Haiti', },
  {  key: 'HN', flag: 'hn', value: 'Honduras', label: 'Honduras', },
  {  key: 'HK', flag: 'hk', value: 'Hong Kong SAR China', label: 'Hong Kong SAR China', },
  {  key: 'HU', flag: 'hu', value: 'Hungary', label: 'Hungary', },
  {  key: 'IS', flag: 'is', value: 'Iceland', label: 'Iceland', },
  {  key: 'IN', flag: 'in', value: 'India', label: 'India', },
  {  key: 'ID', flag: 'id', value: 'Indonesia', label: 'Indonesia', },
  {  key: 'IR', flag: 'ir', value: 'Iran', label: 'Iran', },
  {  key: 'IQ', flag: 'iq', value: 'Iraq', label: 'Iraq', },
  {  key: 'IE', flag: 'ie', value: 'Ireland', label: 'Ireland', },
  {  key: 'IL', flag: 'il', value: 'Israel', label: 'Israel', },
  {  key: 'IT', flag: 'it', value: 'Italy', label: 'Italy', },
  {  key: 'JM', flag: 'jm', value: 'Jamaica', label: 'Jamaica', },
  {  key: 'JP', flag: 'jp', value: 'Japan', label: 'Japan', },
  {  key: 'JO', flag: 'jo', value: 'Jordan', label: 'Jordan', },
  {  key: 'KZ', flag: 'kz', value: 'Kazakhstan', label: 'Kazakhstan', },
  {  key: 'KE', flag: 'ke', value: 'Kenya', label: 'Kenya', },
  {  key: 'KI', flag: 'ki', value: 'Kiribati', label: 'Kiribati', },
  {  key: 'KW', flag: 'kw', value: 'Kuwait', label: 'Kuwait', },
  {  key: 'KG', flag: 'kg', value: 'Kyrgyzstan', label: 'Kyrgyzstan', },
  {  key: 'LA', flag: 'la', value: 'Laos', label: 'Laos', },
  {  key: 'LV', flag: 'lv', value: 'Latvia', label: 'Latvia', },
  {  key: 'LB', flag: 'lb', value: 'Lebanon', label: 'Lebanon', },
  {  key: 'LS', flag: 'ls', value: 'Lesotho', label: 'Lesotho', },
  {  key: 'LR', flag: 'lr', value: 'Liberia', label: 'Liberia', },
  {  key: 'LY', flag: 'ly', value: 'Libya', label: 'Libya', },
  {  key: 'LI', flag: 'li', value: 'Liechtenstein', label: 'Liechtenstein', },
  {  key: 'LT', flag: 'lt', value: 'Lithuania', label: 'Lithuania', },
  {  key: 'LU', flag: 'lu', value: 'Luxembourg', label: 'Luxembourg', },
  {  key: 'MO', flag: 'mo', value: 'Macau SAR China', label: 'Macau SAR China', },
  {  key: 'MK', flag: 'mk', value: 'Macedonia', label: 'Macedonia', },
  {  key: 'MG', flag: 'mg', value: 'Madagascar', label: 'Madagascar', },
  {  key: 'MW', flag: 'mw', value: 'Malawi', label: 'Malawi', },
  {  key: 'MY', flag: 'my', value: 'Malaysia', label: 'Malaysia', },
  {  key: 'MV', flag: 'mv', value: 'Maldives', label: 'Maldives', },
  {  key: 'ML', flag: 'ml', value: 'Mali', label: 'Mali', },
  {  key: 'MT', flag: 'mt', value: 'Malta', label: 'Malta', },
  {  key: 'MH', flag: 'mh', value: 'Marshall Islands', label: 'Marshall Islands', },
  {  key: 'MQ', flag: 'mq', value: 'Martinique', label: 'Martinique', },
  {  key: 'MR', flag: 'mr', value: 'Mauritania', label: 'Mauritania', },
  {  key: 'MU', flag: 'mu', value: 'Mauritius', label: 'Mauritius', },
  {  key: 'YT', flag: 'yt', value: 'Mayotte', label: 'Mayotte', },
  {  key: 'MX', flag: 'mx', value: 'Mexico', label: 'Mexico', },
  {  key: 'FM', flag: 'fm', value: 'Micronesia', label: 'Micronesia', },
  {  key: 'MD', flag: 'md', value: 'Moldova', label: 'Moldova', },
  {  key: 'MC', flag: 'mc', value: 'Monaco', label: 'Monaco', },
  {  key: 'MN', flag: 'mn', value: 'Mongolia', label: 'Mongolia', },
  {  key: 'ME', flag: 'me', value: 'Montenegro', label: 'Montenegro', },
  {  key: 'MS', flag: 'ms', value: 'Montserrat', label: 'Montserrat', },
  {  key: 'MA', flag: 'ma', value: 'Morocco', label: 'Morocco', },
  {  key: 'MZ', flag: 'mz', value: 'Mozambique', label: 'Mozambique', },
  {  key: 'MM', flag: 'mm', value: 'Myanmar (Burma)', label: 'Myanmar (Burma)', },
  {  key: 'NA', flag: 'na', value: 'Namibia', label: 'Namibia', },
  {  key: 'NR', flag: 'nr', value: 'Nauru', label: 'Nauru', },
  {  key: 'NP', flag: 'np', value: 'Nepal', label: 'Nepal', },
  {  key: 'NL', flag: 'nl', value: 'Netherlands', label: 'Netherlands', },
  {  key: 'NC', flag: 'nc', value: 'New Caledonia', label: 'New Caledonia', },
  {  key: 'NZ', flag: 'nz', value: 'New Zealand', label: 'New Zealand', },
  {  key: 'NI', flag: 'ni', value: 'Nicaragua', label: 'Nicaragua', },
  {  key: 'NE', flag: 'ne', value: 'Niger', label: 'Niger', },
  {  key: 'NG', flag: 'ng', value: 'Nigeria', label: 'Nigeria', },
  {  key: 'NU', flag: 'nu', value: 'Niue', label: 'Niue', },
  {  key: 'NF', flag: 'nf', value: 'Norfolk Island', label: 'Norfolk Island', },
  {  key: 'KP', flag: 'kp', value: 'North Korea', label: 'North Korea', },
  {  key: 'MP', flag: 'mp', value: 'Northern Mariana Islands', label: 'Northern Mariana Islands', },
  {  key: 'NO', flag: 'no', value: 'Norway', label: 'Norway', },
  {  key: 'OM', flag: 'om', value: 'Oman', label: 'Oman', },
  {  key: 'PK', flag: 'pk', value: 'Pakistan', label: 'Pakistan', },
  {  key: 'PW', flag: 'pw', value: 'Palau', label: 'Palau', },
  {  key: 'PS', flag: 'ps', value: 'Palestinian Territories', label: 'Palestinian Territories', },
  {  key: 'PA', flag: 'pa', value: 'Panama', label: 'Panama', },
  {  key: 'PG', flag: 'pg', value: 'Papua New Guinea', label: 'Papua New Guinea', },
  {  key: 'PY', flag: 'py', value: 'Paraguay', label: 'Paraguay', },
  {  key: 'PE', flag: 'pe', value: 'Peru', label: 'Peru', },
  {  key: 'PH', flag: 'ph', value: 'Philippines', label: 'Philippines', },
  {  key: 'PN', flag: 'pn', value: 'Pitcairn Islands', label: 'Pitcairn Islands', },
  {  key: 'PL', flag: 'pl', value: 'Poland', label: 'Poland', },
  {  key: 'PT', flag: 'pt', value: 'Portugal', label: 'Portugal', },
  {  key: 'PR', flag: 'pr', value: 'Puerto Rico', label: 'Puerto Rico', },
  {  key: 'QA', flag: 'qa', value: 'Qatar', label: 'Qatar', },
  {  key: 'RE', flag: 're', value: 'R\u00e9union', label: 'R\u00e9union', },
  {  key: 'RO', flag: 'ro', value: 'Romania', label: 'Romania', },
  {  key: 'RU', flag: 'ru', value: 'Russia', label: 'Russia', },
  {  key: 'RW', flag: 'rw', value: 'Rwanda', label: 'Rwanda', },
  {  key: 'WS', flag: 'ws', value: 'Samoa', label: 'Samoa', },
  {  key: 'SM', flag: 'sm', value: 'San Marino', label: 'San Marino', },
  {  key: 'ST', flag: 'st', value: 'S\u00e3o Tom\u00e9 & Pr\u00edncipe', label: 'S\u00e3o Tom\u00e9 & Pr\u00edncipe', },
  {  key: 'SA', flag: 'sa', value: 'Saudi Arabia', label: 'Saudi Arabia', },
  {  key: 'SN', flag: 'sn', value: 'Senegal', label: 'Senegal', },
  {  key: 'RS', flag: 'rs', value: 'Serbia', label: 'Serbia', },
  {  key: 'SC', flag: 'sc', value: 'Seychelles', label: 'Seychelles', },
  {  key: 'SL', flag: 'sl', value: 'Sierra Leone', label: 'Sierra Leone', },
  {  key: 'SG', flag: 'sg', value: 'Singapore', label: 'Singapore', },
  {  key: 'SK', flag: 'sk', value: 'Slovakia', label: 'Slovakia', },
  {  key: 'SI', flag: 'si', value: 'Slovenia', label: 'Slovenia', },
  {  key: 'SB', flag: 'sb', value: 'Solomon Islands', label: 'Solomon Islands', },
  {  key: 'SO', flag: 'so', value: 'Somalia', label: 'Somalia', },
  {  key: 'ZA', flag: 'za', value: 'South Africa', label: 'South Africa', },
  {  key: 'GS', flag: 'gs', value: 'South Georgia & South Sandwich Islands', label: 'South Georgia & South Sandwich Islands', },
  {  key: 'KR', flag: 'kr', value: 'South Korea', label: 'South Korea', },
  {  key: 'ES', flag: 'es', value: 'Spain', label: 'Spain', },
  {  key: 'LK', flag: 'lk', value: 'Sri Lanka', label: 'Sri Lanka', },
  {  key: 'SH', flag: 'sh', value: 'St. Helena', label: 'St. Helena', },
  {  key: 'KN', flag: 'kn', value: 'St. Kitts & Nevis', label: 'St. Kitts & Nevis', },
  {  key: 'LC', flag: 'lc', value: 'St. Lucia', label: 'St. Lucia', },
  {  key: 'PM', flag: 'pm', value: 'St. Pierre & Miquelon', label: 'St. Pierre & Miquelon', },
  {  key: 'VC', flag: 'vc', value: 'St. Vincent & Grenadines', label: 'St. Vincent & Grenadines', },
  {  key: 'SD', flag: 'sd', value: 'Sudan', label: 'Sudan', },
  {  key: 'SR', flag: 'sr', value: 'Suriname', label: 'Suriname', },
  {  key: 'SJ', flag: 'sj', value: 'Svalbard & Jan Mayen', label: 'Svalbard & Jan Mayen', },
  {  key: 'SZ', flag: 'sz', value: 'Swaziland', label: 'Swaziland', },
  {  key: 'SE', flag: 'se', value: 'Sweden', label: 'Sweden', },
  {  key: 'CH', flag: 'ch', value: 'Switzerland', label: 'Switzerland', },
  {  key: 'SY', flag: 'sy', value: 'Syria', label: 'Syria', },
  {  key: 'TW', flag: 'tw', value: 'Taiwan', label: 'Taiwan', },
  {  key: 'TJ', flag: 'tj', value: 'Tajikistan', label: 'Tajikistan', },
  {  key: 'TZ', flag: 'tz', value: 'Tanzania', label: 'Tanzania', },
  {  key: 'TH', flag: 'th', value: 'Thailand', label: 'Thailand', },
  {  key: 'TL', flag: 'tl', value: 'Timor-Leste', label: 'Timor-Leste', },
  {  key: 'TG', flag: 'tg', value: 'Togo', label: 'Togo', },
  {  key: 'TK', flag: 'tk', value: 'Tokelau', label: 'Tokelau', },
  {  key: 'TO', flag: 'to', value: 'Tonga', label: 'Tonga', },
  {  key: 'TT', flag: 'tt', value: 'Trinidad & Tobago', label: 'Trinidad & Tobago', },
  {  key: 'TN', flag: 'tn', value: 'Tunisia', label: 'Tunisia', },
  {  key: 'TR', flag: 'tr', value: 'Turkey', label: 'Turkey', },
  {  key: 'TM', flag: 'tm', value: 'Turkmenistan', label: 'Turkmenistan', },
  {  key: 'TC', flag: 'tc', value: 'Turks & Caicos Islands', label: 'Turks & Caicos Islands', },
  {  key: 'TV', flag: 'tv', value: 'Tuvalu', label: 'Tuvalu', },
  {  key: 'UM', flag: 'um', value: 'U.S. Outlying Islands', label: 'U.S. Outlying Islands', },
  {  key: 'VI', flag: 'vi', value: 'U.S. Virgin Islands', label: 'U.S. Virgin Islands', },
  {  key: 'UG', flag: 'ug', value: 'Uganda', label: 'Uganda', },
  {  key: 'UA', flag: 'ua', value: 'Ukraine', label: 'Ukraine', },
  {  key: 'AE', flag: 'ae', value: 'United Arab Emirates', label: 'United Arab Emirates', },
  {  key: 'GB', flag: 'gb', value: 'United Kingdom', label: 'United Kingdom', },
  {  key: 'US', flag: 'us', value: 'United States', label: 'United States', },
  {  key: 'USM', flag: 'us', value: 'United States Minor Outlying Islands', label: 'United States Minor Outlying Islands', },
  {  key: 'UY', flag: 'uy', value: 'Uruguay', label: 'Uruguay', },
  {  key: 'UZ', flag: 'uz', value: 'Uzbekistan', label: 'Uzbekistan', },
  {  key: 'VU', flag: 'vu', value: 'Vanuatu', label: 'Vanuatu', },
  {  key: 'VA', flag: 'va', value: 'Vatican City', label: 'Vatican City', },
  {  key: 'VE', flag: 've', value: 'Venezuela', label: 'Venezuela', },
  {  key: 'VN', flag: 'vn', value: 'Vietnam', label: 'Vietnam', },
  {  key: 'WF', flag: 'wf', value: 'Wallis & Futuna', label: 'Wallis & Futuna', },
  {  key: 'EH', flag: 'eh', value: 'Western Sahara', label: 'Western Sahara', },
  {  key: 'YE', flag: 'ye', value: 'Yemen', label: 'Yemen', },
  {  key: 'ZM', flag: 'zm', value: 'Zambia', label: 'Zambia', },
  {  key: 'ZW', flag: 'zw', value: 'Zimbabw', label: 'Zimbabwe' },
]
